language: rust
rust:
  - 1.21.0
  - stable
  - nightly
sudo: false
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo package
  - cd target/package/unicode-normalization-*
  - cargo test --verbose
notifications:
  email:
    on_success: never
