language: rust
env:
  - RUSTFLAGS="--cfg bloaty_test"
rust:
  - 1.21.0
  - stable
  - nightly
sudo: false
script:
  - cargo build --verbose
  - cargo test --verbose
notifications:
  email:
    on_success: never
